# Generated by Django 5.0.7 on 2024-07-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('tel', models.TextField(max_length=50, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Докторы',
            },
        ),
    ]
